export const VALID_USE_CASES = [
  'MARKETING',
  'ACCOUNT_NOTIFICATION',
  'CUSTOMER_CARE',
  'DELIVERY_NOTIFICATION',
  'FRAUD_ALERT',
  'HIGHER_EDUCATION',
  'LOW_VOLUME',
  'MIXED',
  'POLLING_VOTING',
  'PUBLIC_SERVICE_ANNOUNCEMENT',
  'SECURITY_ALERT',
  'TWO_FACTOR_AUTH',
  'CHARITY',
  'EMERGENCY',
  'POLITICAL',
  'SWEEPSTAKE',
] as const;

export type UseCaseType = (typeof VALID_USE_CASES)[number];
